/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gup_test_zerocopy_demo_JniTest */

#ifndef _Included_gup_test_zerocopy_demo_JniTest
#define _Included_gup_test_zerocopy_demo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gup_test_zerocopy_demo_JniTest
 * Method:    getFileDescriptor
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_gup_test_zerocopy_demo_JniTest_getFileDescriptor
  (JNIEnv *env, jobject obj, jstring path, jint length);

#ifdef __cplusplus
}
#endif
#endif
