/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gup_test_zerocopy_demo_DomainTest */

#ifndef _Included_gup_test_zerocopy_demo_DomainTest
#define _Included_gup_test_zerocopy_demo_DomainTest
#ifdef __cplusplus
extern "C" {
#endif
#undef gup_test_zerocopy_demo_DomainTest_LENGTH
#define gup_test_zerocopy_demo_DomainTest_LENGTH 16LL
/*
 * Class:     gup_test_zerocopy_demo_DomainTest
 * Method:    sendFileDescriptor
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_gup_test_zerocopy_demo_DomainTest_sendFileDescriptor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     gup_test_zerocopy_demo_DomainTest
 * Method:    getFileDescriptor
 * Signature: ()Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_gup_test_zerocopy_demo_DomainTest_getFileDescriptor
  (JNIEnv *, jobject);

/*
 * Class:     gup_test_zerocopy_demo_DomainTest
 * Method:    mmap
 * Signature: (Ljava/io/FileDescriptor;J)J
 */
JNIEXPORT jlong JNICALL Java_gup_test_zerocopy_demo_DomainTest_mmap
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     gup_test_zerocopy_demo_DomainTest
 * Method:    unmap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_gup_test_zerocopy_demo_DomainTest_unmap
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
